/**
 * Country name mappings and utilities
 */

/** Comprehensive country code to name mapping */
export const COUNTRY_NAMES: Record<string, string> = {
  // Major countries
  US: "United States",
  GB: "United Kingdom",
  CA: "Canada",
  AU: "Australia",
  DE: "Germany",
  FR: "France",
  IN: "India",
  JP: "Japan",
  CN: "China",
  BR: "Brazil",
  MX: "Mexico",
  IT: "Italy",
  ES: "Spain",
  RU: "Russia",
  KR: "South Korea",

  // European Union
  NL: "Netherlands",
  SE: "Sweden",
  NO: "Norway",
  DK: "Denmark",
  FI: "Finland",
  CH: "Switzerland",
  AT: "Austria",
  BE: "Belgium",
  IE: "Ireland",
  PT: "Portugal",
  GR: "Greece",
  PL: "Poland",
  CZ: "Czech Republic",
  HU: "Hungary",
  RO: "Romania",
  BG: "Bulgaria",
  HR: "Croatia",
  SI: "Slovenia",
  SK: "Slovakia",
  LT: "Lithuania",
  LV: "Latvia",
  EE: "Estonia",
  LU: "Luxembourg",
  MT: "Malta",
  CY: "Cyprus",
  IS: "Iceland",
  TR: "Turkey",

  // Middle East & Africa
  IL: "Israel",
  SA: "Saudi Arabia",
  AE: "United Arab Emirates",
  EG: "Egypt",
  ZA: "South Africa",
  NG: "Nigeria",
  KE: "Kenya",
  GH: "Ghana",
  MA: "Morocco",
  TN: "Tunisia",
  DZ: "Algeria",
  ET: "Ethiopia",
  UG: "Uganda",
  TZ: "Tanzania",
  ZW: "Zimbabwe",
  BW: "Botswana",
  ZM: "Zambia",
  MW: "Malawi",
  MZ: "Mozambique",
  MG: "Madagascar",
  MU: "Mauritius",
  RE: "Reunion",
  SC: "Seychelles",
  SN: "Senegal",
  ML: "Mali",
  BF: "Burkina Faso",
  NE: "Niger",
  TD: "Chad",
  CF: "Central African Republic",
  CM: "Cameroon",
  GQ: "Equatorial Guinea",
  GA: "Gabon",
  CG: "Congo",
  CD: "DR Congo",
  AO: "Angola",

  // Asia Pacific
  TH: "Thailand",
  VN: "Vietnam",
  SG: "Singapore",
  MY: "Malaysia",
  ID: "Indonesia",
  PH: "Philippines",
  MM: "Myanmar",
  KH: "Cambodia",
  LA: "Laos",
  BD: "Bangladesh",
  PK: "Pakistan",
  LK: "Sri Lanka",
  NP: "Nepal",
  BT: "Bhutan",
  MV: "Maldives",
  AF: "Afghanistan",
  IR: "Iran",
  IQ: "Iraq",
  SY: "Syria",
  LB: "Lebanon",
  JO: "Jordan",
  PS: "Palestine",
  KW: "Kuwait",
  BH: "Bahrain",
  QA: "Qatar",
  OM: "Oman",
  YE: "Yemen",
  UZ: "Uzbekistan",
  KZ: "Kazakhstan",
  KG: "Kyrgyzstan",
  TJ: "Tajikistan",
  TM: "Turkmenistan",
  MN: "Mongolia",
  GE: "Georgia",
  AM: "Armenia",
  AZ: "Azerbaijan",

  // Eastern Europe
  BY: "Belarus",
  UA: "Ukraine",
  MD: "Moldova",
  RS: "Serbia",
  ME: "Montenegro",
  BA: "Bosnia and Herzegovina",
  MK: "North Macedonia",
  AL: "Albania",
  XK: "Kosovo",

  // Americas
  AR: "Argentina",
  CL: "Chile",
  PE: "Peru",
  CO: "Colombia",
  VE: "Venezuela",
  EC: "Ecuador",
  BO: "Bolivia",
  PY: "Paraguay",
  UY: "Uruguay",
  GY: "Guyana",
  SR: "Suriname",
  GF: "French Guiana",
  FK: "Falkland Islands",

  // Oceania
  NZ: "New Zealand",
  FJ: "Fiji",
  PG: "Papua New Guinea",
  NC: "New Caledonia",
  VU: "Vanuatu",
  SB: "Solomon Islands",
  TO: "Tonga",
  WS: "Samoa",
  KI: "Kiribati",
  TV: "Tuvalu",
  NR: "Nauru",
  PW: "Palau",
  FM: "Micronesia",
  MH: "Marshall Islands",

  // Additional territories
  AD: "Andorra",
  AI: "Anguilla",
  AQ: "Antarctica",
  AG: "Antigua and Barbuda",
  AW: "Aruba",
  BS: "Bahamas",
  BB: "Barbados",
  BZ: "Belize",
  BJ: "Benin",
  BM: "Bermuda",
  BN: "Brunei",
  BV: "Bouvet Island",
  IO: "British Indian Ocean Territory",
  VG: "British Virgin Islands",
  CV: "Cape Verde",
  KY: "Cayman Islands",
  CX: "Christmas Island",
  CC: "Cocos Islands",
  KM: "Comoros",
  CK: "Cook Islands",
  CR: "Costa Rica",
  CI: "Côte d'Ivoire",
  CU: "Cuba",
  CW: "Curaçao",
  DJ: "Djibouti",
  DM: "Dominica",
  DO: "Dominican Republic",
  ER: "Eritrea",
  FO: "Faroe Islands",
  GL: "Greenland",
  GD: "Grenada",
  GP: "Guadeloupe",
  GU: "Guam",
  GT: "Guatemala",
  GG: "Guernsey",
  GN: "Guinea",
  GW: "Guinea-Bissau",
  HT: "Haiti",
  HM: "Heard Island",
  VA: "Vatican City",
  HN: "Honduras",
  HK: "Hong Kong",
  IM: "Isle of Man",
  JM: "Jamaica",
  JE: "Jersey",
  LI: "Liechtenstein",
  MO: "Macao",
  MQ: "Martinique",
  MR: "Mauritania",
  YT: "Mayotte",
  MC: "Monaco",
  MS: "Montserrat",
  NA: "Namibia",
  NU: "Niue",
  NF: "Norfolk Island",
  MP: "Northern Mariana Islands",
  PA: "Panama",
  PF: "French Polynesia",
  PN: "Pitcairn",
  PR: "Puerto Rico",
  BL: "Saint Barthélemy",
  SH: "Saint Helena",
  KN: "Saint Kitts and Nevis",
  LC: "Saint Lucia",
  MF: "Saint Martin",
  PM: "Saint Pierre and Miquelon",
  VC: "Saint Vincent and the Grenadines",
  SM: "San Marino",
  ST: "São Tomé and Príncipe",
  SL: "Sierra Leone",
  SX: "Sint Maarten",
  SO: "Somalia",
  GS: "South Georgia",
  SS: "South Sudan",
  SJ: "Svalbard and Jan Mayen",
  SZ: "Eswatini",
  TC: "Turks and Caicos Islands",
  TK: "Tokelau",
  TT: "Trinidad and Tobago",
  TW: "Taiwan",
  VI: "U.S. Virgin Islands",
  UM: "U.S. Outlying Islands",
  WF: "Wallis and Futuna",
  EH: "Western Sahara",
} as const;

/** Special cases for uncommon country codes */
export const SPECIAL_COUNTRY_CASES: Record<string, string> = {
  AC: "Ascension Island",
  BQ: "Caribbean Netherlands",
  EZ: "Eurozone",
  TA: "Tristan da Cunha",
  UN: "United Nations",
  XA: "Private Use Area",
  XB: "Private Use Area",
  XC: "Private Use Area",
} as const;

/**
 * Gets the display name for a country code
 * @param countryCode - ISO country code
 * @returns Human readable country name
 */
export const getCountryName = (countryCode: string): string => {
  // Try comprehensive mapping first
  if (COUNTRY_NAMES[countryCode]) {
    return COUNTRY_NAMES[countryCode];
  }

  // Handle special cases
  if (SPECIAL_COUNTRY_CASES[countryCode]) {
    return SPECIAL_COUNTRY_CASES[countryCode];
  }

  // Fallback for unknown codes
  return `${countryCode} Region`;
};
